import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers';
import { jwtVerify } from 'jose';
import Link from 'next/link';
import LogoutButton from '@/components/LogoutButton';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('token')?.value;
  let role: string | null = null;
  let username: string | null = null;
  
  if (token) {
    try {
      const secretKey = process.env.JWT_SECRET || 'super_secret_jwt_key_replace_me_later';
      const encodedKey = new TextEncoder().encode(secretKey);
      const { payload } = await jwtVerify(token, encodedKey);
      role = payload.role as string;
      username = payload.username as string;
    } catch (e) {
      // invalid token
    }
  }

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {token && (
          <nav className="bg-slate-900 border-b border-slate-800">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between h-16">
                <div className="flex">
                  <div className="flex-shrink-0 flex items-center">
                    <span className="font-bold text-xl text-blue-500">OFD Dashboard</span>
                  </div>
                  <div className="hidden sm:ml-6 sm:flex sm:space-x-8">
                    <Link href="/" className="border-transparent text-slate-400 hover:text-slate-200 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                      Home
                    </Link>
                    {role === 'admin' && (
                      <>
                        <Link href="/admin/dashboard" className="border-transparent text-slate-400 hover:text-slate-200 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                          Wallet Dashboard
                        </Link>
                        <Link href="/admin/users" className="border-transparent text-slate-400 hover:text-slate-200 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                          Users
                        </Link>
                        <Link href="/admin/logs" className="border-transparent text-slate-400 hover:text-slate-200 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                          Audit Logs
                        </Link>
                      </>
                    )}
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <span className="text-sm text-slate-400">Welcome, <span className="text-slate-200 font-medium">{username}</span></span>
                  <LogoutButton />
                </div>
              </div>
            </div>
          </nav>
        )}
        <main className="flex-1 p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
